
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ElanMan Code
email: ben@elanman.com
description: > # this means to ignore newlines until "baseurl:"
  Code By ElanMan
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://code.elanman.com" # the base hostname & protocol for your site
twitter_username: elanman
github_username:  elanman

# Build settings
markdown: kramdown
